# Generated by Django 2.2 on 2020-07-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200611_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_info',
            name='attachment',
        ),
        migrations.AddField(
            model_name='account_normal',
            name='approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Accountnormal_approve_user', to='api.UserInfo'),
        ),
        migrations.AddField(
            model_name='account_normal',
            name='approvetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account_project',
            name='approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Accountproject_approve_user', to='api.UserInfo'),
        ),
        migrations.AddField(
            model_name='account_project',
            name='approvetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_normal',
            name='account_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('lujin', models.CharField(max_length=64)),
                ('hetong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Contract_info')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Account_view',
        #     fields=[
        #         ('type', models.CharField(max_length=2)),
        #         ('sysid', models.CharField(max_length=64, primary_key=True, serialize=False)),
        #         ('tableid', models.IntegerField(max_length=32)),
        #         ('cause', models.CharField(max_length=64)),
        #         ('money', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('account_date', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('finish_flag', models.IntegerField()),
        #         ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserInfo')),
        #         ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Project_info')),
        #     ],
        #     options={
        #         'db_table': 'account_view',
        #     },
        # ),
    ]
