# Generated by Django 2.2 on 2020-08-27 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200716_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_plan',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='contract_plan',
            name='money_type',
        ),
        migrations.AddField(
            model_name='contract_plan',
            name='contract_type',
            field=models.CharField(choices=[(0, '发票类型/未完成'), (1, '资金类型/已完成')], default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract_plan',
            name='finish_type',
            field=models.CharField(choices=[(0, '发票类型/未完成'), (1, '资金类型/已完成')], default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        # migrations.CreateModel(
        #     name='Account_view',
        #     fields=[
        #         ('type', models.CharField(max_length=2)),
        #         ('sysid', models.CharField(max_length=64, primary_key=True, serialize=False)),
        #         ('tableid', models.IntegerField(max_length=32)),
        #         ('cause', models.CharField(max_length=64)),
        #         ('money', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('account_date', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('finish_flag', models.IntegerField()),
        #         ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserInfo')),
        #         ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Project_info')),
        #     ],
        #     options={
        #         'db_table': 'account_view',
        #     },
        # ),
    ]
