# Generated by Django 3.1.2 on 2020-10-30 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200924_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_project',
            name='end_addr',
            field=models.CharField(default=datetime.datetime(2020, 10, 30, 11, 54, 58, 911034), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account_project',
            name='start_addr',
            field=models.CharField(default=datetime.datetime(2020, 10, 30, 11, 55, 12, 733252), max_length=64),
            preserve_default=False,
        ),
        # migrations.CreateModel(
        #     name='Account_view',
        #     fields=[
        #         ('type', models.CharField(max_length=2)),
        #         ('sysid', models.CharField(max_length=64, primary_key=True, serialize=False)),
        #         ('tableid', models.IntegerField(max_length=32)),
        #         ('cause', models.CharField(max_length=64)),
        #         ('money', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('account_date', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('finish_flag', models.IntegerField()),
        #         ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.userinfo')),
        #         ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project_info')),
        #     ],
        #     options={
        #         'db_table': 'account_view',
        #     },
        # ),
    ]
