# Generated by Django 3.2 on 2022-05-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='商品名')),
                ('detail', models.CharField(default='', max_length=255, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('img', models.CharField(default='', max_length=100, verbose_name='商品图片')),
            ],
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(default='', max_length=100, verbose_name='商铺位置')),
                ('is_rented', models.BooleanField(default=False, verbose_name='是否租出')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='缴费价位id')),
                ('money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='费用')),
            ],
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='租商铺价位id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='商铺名称')),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.market')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.payment')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='商品数量')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.goods')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.shop')),
            ],
        ),
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='商户名')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='余额')),
                ('shops', models.ManyToManyField(to='mall.shop')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.rent'),
        ),
    ]
