# Generated by Django 3.2 on 2022-05-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.payment'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='商铺种类'),
        ),
    ]
