# Generated by Django 3.2 on 2022-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20220501_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('sex', models.BooleanField(null=True)),
                ('tel', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(max_length=12, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tel',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='username',
            field=models.CharField(max_length=12, null=True, verbose_name='用户名'),
        ),
    ]
