# Generated by Django 3.2 on 2022-05-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20220501_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='shops',
        ),
        migrations.AddField(
            model_name='shop',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.merchant'),
        ),
    ]
