# Generated by Django 3.2 on 2022-05-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20220501_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='payelec',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电费价位id')),
                ('money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='费用')),
            ],
        ),
        migrations.CreateModel(
            name='paywater',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='水费价位id')),
                ('money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='费用')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.payelec'),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
