# Generated by Django 3.2 on 2022-05-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20220503_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='payment',
            new_name='payelec',
        ),
        migrations.AddField(
            model_name='shop',
            name='paywater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.paywater'),
        ),
    ]
