# Generated by Django 3.2 on 2022-05-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20220503_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='payelec',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='paywater',
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10)),
                ('payelec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.payelec')),
                ('paywater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.paywater')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.type'),
        ),
    ]
