# Generated by Django 3.2 on 2022-05-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20220503_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='typename',
        ),
    ]
