# Generated by Django 2.2 on 2020-06-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=64)),
                ('contract_type', models.CharField(choices=[(1, '收款合同'), (2, '付款合同')], max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_start', models.DateField()),
                ('Date_end', models.DateField(null=True)),
                ('attachment', models.CharField(max_length=128, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('explain', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(default='技术部', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=128, unique=True)),
                ('entity_addr', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('bank_addr', models.CharField(max_length=64, null=True)),
                ('bank_number', models.CharField(max_length=64, null=True)),
                ('shuiHao', models.CharField(max_length=64, null=True)),
                ('explain', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')])),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(default='无名氏', max_length=32, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidize_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Project_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_customer', to='api.Entity_info')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_owner', to='api.Entity_info')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='dept_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_manager_user', to='api.UserInfo'),
        ),
        migrations.CreateModel(
            name='Contract_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plan', models.DateField()),
                ('money_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_type', models.CharField(choices=[(0, '未开发票/未付款'), (1, '已开发票/已付款')], max_length=64)),
                ('money_type', models.CharField(choices=[(0, '未开发票/未付款'), (1, '已开发票/已付款')], max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Contract_info')),
            ],
        ),
        migrations.AddField(
            model_name='contract_info',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_entity', to='api.Entity_info'),
        ),
        migrations.AddField(
            model_name='contract_info',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Project_info'),
        ),
        migrations.AddField(
            model_name='contract_info',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Entity_info'),
        ),
        migrations.CreateModel(
            name='Account_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhushu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_traffic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sumDate', models.IntegerField()),
                ('sumButie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('account_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('explain', models.CharField(max_length=64)),
                ('finish_flag', models.CharField(choices=[(0, '未完成报销'), (1, '已完成报销')], default=0, max_length=64)),
                ('Type_traffic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Traffic_type')),
                ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserInfo')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Project_info')),
            ],
        ),
        migrations.CreateModel(
            name='Account_normal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_date', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.CharField(max_length=64)),
                ('finish_flag', models.CharField(choices=[(0, '未完成报销'), (1, '已完成报销')], default=0, max_length=64)),
                ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserInfo')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Project_info')),
            ],
        ),
    ]
